type Query {
  students: [Student!]!
  student(id: ID!): Student
}

type Student {
  id: ID!
  first_name: String
  last_name: String
  groups: [Group!]!
  full_name: String
}

type Mutation {
  createStudent(input: CreateStudentInput!): Student!
  updateStudent(id: ID!, input: UpdateStudentInput!): Student!
  removeStudent(id: ID!): Student!
}

type Subscription {
  studentCreated: Student!
}

input CreateStudentInput {
  first_name: String!
  last_name: String!
}

input UpdateStudentInput {
  first_name: String
  last_name: String
}