type Comment {
  id: ID!
  text: String
  user: User
  post: Post
}

type Query {
  comments: [Comment!]!
  comment(id: ID!): Comment!
}

type Mutation {
  createComment(input: CreateCommentInput!): Comment!
  updateComment(id: ID!, input: UpdateCommentInput!): Comment!
  removeComment(id: ID!): Comment!
}

type Subscription {
  commentCreated: Comment!
}

input CreateCommentInput {
  text: String!
  user_id: ID!
  post_id: ID!
}

input UpdateCommentInput {
  text: String
  user_id: ID
  post_id: ID
}