type Mutation {
  addStudentToGroup(input: AddStudentToGroupInput!): String!
  updateStudentOrGroup(id: ID!, input: UpdateStudentOrGroupInput!): String!
  removeStudentfromGroup(id: ID!): String!
}

input AddStudentToGroupInput {
  student_id: ID!
  group_id: ID!
}

input UpdateStudentOrGroupInput {
  student_id: ID
  group_id: ID
}