type Query {
  groups: [Group!]!
  group(id: ID!): Group!
}

type Group {
  id: ID!
  name: String
  # students: [Student!]!
}

type Mutation {
  createGroup(input: CreateGroupInput!): Group!
  updateGroup(id: ID!, input: UpdateGroupInput!): Group!
  removeGroup(id: ID!): Group!
}

type Subscription {
  groupCreated: Group!
}

input CreateGroupInput {
  name: String!
}

input UpdateGroupInput {
  name: String
}