type Category {
  id: ID!
  name: String
  # meals: [Meal!]!
}

type Query {
  categories: [Category!]!
  category(id: ID!): Category! 
}

type Mutation {
  createCategory(input: CreateCategoryInput!): Category!
  updateCategory(id: ID!, input: UpdateCategoryInput!): Category!
  removeCategory(id: ID!): Category!
}

type Subscription {
  categoryCreated: Category!
}

input CreateCategoryInput {
  name: String!
}

input UpdateCategoryInput {
  name: String
}